<a href="https://colab.research.google.com/github/thecrazyphysicist369/Content-Emotion-Model/blob/main/code/Emotional_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random

In [3]:
def norm_ev(vec):
  vec_new = []
  sum=np.sum(vec)
  for i in vec:
    item = (i*100)/sum
    vec_new.append(item)
  return np.array(vec_new)



In [4]:
def gen_sample_ev(n):
  vector = []
  for i in range(n):
    vector.append(random.randint(10,30))
  return (norm_ev(vector))


In [5]:
sample = gen_sample_ev(4)
print(sample)

[14.44444444 30.         32.22222222 23.33333333]


In [8]:
def gen_sample_evm(n, m):
  vector=[]
  for i in range(m):
    vector.append(gen_sample_ev(n))
  return np.array(vector)

In [10]:
x = gen_sample_evm(3,5)
print(x)
for i in x:
  print(i)

[[35.29411765 37.25490196 27.45098039]
 [21.875      40.625      37.5       ]
 [38.46153846 34.61538462 26.92307692]
 [16.66666667 39.39393939 43.93939394]
 [21.05263158 45.61403509 33.33333333]]
[35.29411765 37.25490196 27.45098039]
[21.875 40.625 37.5  ]
[38.46153846 34.61538462 26.92307692]
[16.66666667 39.39393939 43.93939394]
[21.05263158 45.61403509 33.33333333]
