<a href="https://colab.research.google.com/github/thecrazyphysicist369/Content-Emotion-Model/blob/main/code/Emotional_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy 
import numpy as np 
  
# creating a 1-D list (Horizontal) 
list1 = [1, 2, 3] 
  
# creating a 1-D list (Vertical) 
list2 = [[10], 
        [20], 
        [30]] 
  
# creating a vector1 
# vector as row 
vector1 = np.array(list1) 
  
# creating a vector 2 
# vector as column 
vector2 = np.array(list2) 
  
  
# showing horizontal vector 
print("Horizontal Vector") 
print(vector1) 
print(type(vector1))
print("----------------") 
  
# showing vertical vector 
print("Vertical Vector") 
print(vector2) 

Horizontal Vector
[1 2 3]
<class 'numpy.ndarray'>
----------------
Vertical Vector
[[10]
 [20]
 [30]]


In [ ]:
print(vector1*vector2)

[[10 20 30]
 [20 40 60]
 [30 60 90]]
